on:
  push:
name: action
jobs:
  hello-world:
    name: Un job para saludar
    runs-on: ubuntu-latest
    steps:
      - name: Step Hola Mundo
        id: hello
        uses: pablokbs/hello-world-docker-action@v2
        with:
          who-to-greet: "Pelades"
      - name: Usar el output
        run: echo "La fecha fue ${{ steps.hello.outputs.time }}"
